#FROM registry.access.redhat.com/ubi10/nodejs-22:1787044470
FROM node:22-slim

USER root
RUN apt update
RUN apt-get install -y git ripgrep
RUN npm install -g npm@12.0.2

RUN useradd -m -u 1002 scan
USER scan

WORKDIR /home/scan/

RUN npm config set cache /home/scan/.npm/ 
RUN npm add deepsec@2.3.8
RUN npm install-scripts approve @google/genai@1.52.0
RUN npm install-scripts approve protobufjs@7.6.6
RUN npm config set offline true 

COPY --chmod=744 deepsec-setup.sh /home/scan/deepsec-setup.sh

COPY --chmod=744 deepsec-report.sh /home/scan/deepsec-report.sh

# TEMPORARY TESTING -- REMOVE
COPY models.json /home/scan/env/models.json

ENV REPO_DIR='/repo'
ENV WORK_DIR='/work'
ENV VERCEL_OIDC_TOKEN=123123
ENV DEEPSEC_AGENT_DEBUG=0
ENV LLMAPIKEY=1234OVERRIDE
ENV PROJECT_ID=0
ENV MODEL_NAME='vllm/Qwen3.6-35B-A3B'
ENV MODEL_BASE_URL='https://maas.example.com/v1'

WORKDIR /home/scan/

ENTRYPOINT ["bash","/home/scan/deepsec-setup.sh"]